-- 1. USER와 테이블스페이스
-- 1.1 테이블스페이스 생성
------ 기본적으로 DATA,IDX,TEMP로 나뉜다.
CREATE TABLESPACE PLATFORM_DATA
DATAFILE '/u01/app/oracle/oradata/PLATFORM_DATA.DBF' SIZE 100M
AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE PLATFORM_IDX
DATAFILE '/u01/app/oracle/oradata/PLATFORM_IDX.DBF' SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TEMPORARY TABLESPACE PLATFORM_TMP
TEMPFILE '/u01/app/oracle/oradata/PLATFORM_TMP.DBF' SIZE 50M
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

-- 1.2 유저 생성  
CREATE USER platform IDENTIFIED BY platform
DEFAULT TABLESPACE PLATFORM_DATA
TEMPORARY TABLESPACE PLATFORM_TMP
PROFILE DEFAULT
ACCOUNT UNLOCK;

-- 1.3 유저 권한 설정
GRANT RESOURCE TO PLATFORM;
GRANT CONNECT TO PLATFORM;
GRANT CREATE VIEW TO PLATFORM;
GRANT CREATE SYNONYM TO PLATFORM;
GRANT DBA TO PLATFORM;