--------------------------------------------------------
--  DDL for Table T_USER
--------------------------------------------------------
CREATE TABLE "T_USER" 
   ("USER_ID" VARCHAR2(20) , 
	"USER_NM" VARCHAR2(100), 
	"USER_GROUP" VARCHAR2(100), 
	"IS_USE" VARCHAR2(1) DEFAULT 'Y',
	"IS_LOCK" VARCHAR2(1) DEFAULT 'N',
	"USER_PWD" VARCHAR2(1000), 
	"CREATE_USER" VARCHAR2(100), 
	"CREATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(100), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_DATA";
COMMENT ON COLUMN "T_USER"."USER_ID" IS '사용자아이디';
COMMENT ON COLUMN "T_USER"."USER_NM" IS '사용자명';
COMMENT ON COLUMN "T_USER"."USER_GROUP" IS '사용자그룹';
COMMENT ON COLUMN "T_USER"."IS_USE" IS '사용여부';
COMMENT ON COLUMN "T_USER"."IS_LOCK" IS '잠금여부';
COMMENT ON COLUMN "T_USER"."USER_PWD" IS '비밀번호';
COMMENT ON COLUMN "T_USER"."CREATE_USER" IS '생성자';
COMMENT ON COLUMN "T_USER"."CREATE_DATE" IS '생성일';
COMMENT ON COLUMN "T_USER"."UPDATE_USER" IS '수정자';
COMMENT ON COLUMN "T_USER"."UPDATE_DATE" IS '수정일';
--------------------------------------------------------
--  DDL for Table T_MENU
--------------------------------------------------------
CREATE TABLE "T_MENU" 
   (	"MENU_SEQ" NUMBER, 
	"MENU_NM" VARCHAR2(100), 
	"MENU_URL" VARCHAR2(200), 
	"PARENT_MENU" NUMBER DEFAULT 0, 
	"DEPTH" NUMBER, 
	"ORDER_NUM" NUMBER, 
	"ORDER_GROUP" NUMBER, 
	"CREATE_USER" VARCHAR2(100), 
	"CREATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(100), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_DATA";
COMMENT ON COLUMN "T_MENU"."MENU_SEQ" IS '메뉴번호';
COMMENT ON COLUMN "T_MENU"."MENU_NM" IS '메뉴명';
COMMENT ON COLUMN "T_MENU"."MENU_URL" IS '메뉴URL';
COMMENT ON COLUMN "T_MENU"."PARENT_MENU" IS '부모메뉴번호';
COMMENT ON COLUMN "T_MENU"."DEPTH" IS '단계';
--필요한가?
COMMENT ON COLUMN "T_MENU"."ORDER_NUM" IS '조회순서';
COMMENT ON COLUMN "T_MENU"."ORDER_GROUP" IS '그룹순서';
COMMENT ON COLUMN "T_MENU"."CREATE_USER" IS '생성자';
COMMENT ON COLUMN "T_MENU"."CREATE_DATE" IS '생성일';
COMMENT ON COLUMN "T_MENU"."UPDATE_USER" IS '수정자';
COMMENT ON COLUMN "T_MENU"."UPDATE_DATE" IS '수정일';
--------------------------------------------------------
--  DDL for Table T_CODE
--------------------------------------------------------
CREATE TABLE "T_CODE" 
   (	"CODE" VARCHAR2(6), 
	"CODE_NM" VARCHAR2(50), 
	"CODE_NM_ENG" VARCHAR2(50), 
	"NOTE" VARCHAR2(200), 
	"REMARK" VARCHAR2(1000),
	"PARENT_CODE" VARCHAR2(50),  
	"ORDER_NUM" NUMBER,  
	"DEPTH" NUMBER, 
	"IS_USE" VARCHAR2(1) DEFAULT 'Y', 
	"IS_LOCK" VARCHAR2(1) DEFAULT 'N', 
	"CREATE_USER" VARCHAR2(100), 
	"CREATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(100), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_DATA";
COMMENT ON COLUMN "T_CODE"."CODE" IS '코드';
COMMENT ON COLUMN "T_CODE"."CODE_NM" IS '코드명';
COMMENT ON COLUMN "T_CODE"."CODE_NM_ENG" IS '코드영문명';
COMMENT ON COLUMN "T_CODE"."NOTE" IS '코드설명';
COMMENT ON COLUMN "T_CODE"."REMARK" IS '비고';
COMMENT ON COLUMN "T_CODE"."PARENT_CODE" IS '부모코드';
COMMENT ON COLUMN "T_CODE"."ORDER_NUM" IS '조회순서';
COMMENT ON COLUMN "T_CODE"."DEPTH" IS '단계';
COMMENT ON COLUMN "T_CODE"."IS_USE" IS '사용여부';
COMMENT ON COLUMN "T_CODE"."IS_LOCK" IS '잠금여부';
COMMENT ON COLUMN "T_CODE"."CREATE_USER" IS '생성자';
COMMENT ON COLUMN "T_CODE"."CREATE_DATE" IS '생성일';
COMMENT ON COLUMN "T_CODE"."UPDATE_USER" IS '수정자';
COMMENT ON COLUMN "T_CODE"."UPDATE_DATE" IS '수정일';
--------------------------------------------------------
--  DDL for Table T_MANUAL
--------------------------------------------------------
CREATE TABLE "T_MANUAL" 
   (	"MANUAL_SEQ" NUMBER, 
	"SUBJECT" VARCHAR2(50), 
    "REMARK" VARCHAR2(100),
    "MANUAL_FILE_SEQ" NUMBER, 
	"CREATE_USER" VARCHAR2(100), 
	"CREATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(100), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_DATA";
COMMENT ON COLUMN "T_MANUAL"."MANUAL_SEQ" IS '메뉴얼순번';
COMMENT ON COLUMN "T_MANUAL"."SUBJECT" IS '제목';
COMMENT ON COLUMN "T_MANUAL"."REMARK" IS '비고';
COMMENT ON COLUMN "T_MANUAL"."MANUAL_FILE_SEQ" IS '파일순번';
COMMENT ON COLUMN "T_MANUAL"."CREATE_USER" IS '생성자';
COMMENT ON COLUMN "T_MANUAL"."CREATE_DATE" IS '생성일';
COMMENT ON COLUMN "T_MANUAL"."UPDATE_USER" IS '수정자';
COMMENT ON COLUMN "T_MANUAL"."UPDATE_DATE" IS '수정일';
--------------------------------------------------------
--  DDL for Table T_FILE
--------------------------------------------------------
CREATE TABLE "T_FILE" 
   (	"FILE_SEQ" NUMBER, 
	"FILE_PATH" VARCHAR2(100), 
	"FILE_NAME" VARCHAR2(100), 
	"FILE_CONTENT" VARCHAR2(100), 
	"FILE_EXT" VARCHAR2(10), 
	"FILE_TYPE" VARCHAR2(10), 
	"MASTER_FILE_SEQ" NUMBER,
	"CREATE_USER" VARCHAR2(100), 
	"CREATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(100), 
	"UPDATE_DATE" DATE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_DATA";
;
COMMENT ON COLUMN "T_FILE"."FILE_SEQ" IS '파일순번';
COMMENT ON COLUMN "T_FILE"."FILE_PATH" IS '파일패스';
COMMENT ON COLUMN "T_FILE"."FILE_NAME" IS '파일명';
COMMENT ON COLUMN "T_FILE"."FILE_CONTENT" IS '파일내용';
COMMENT ON COLUMN "T_FILE"."FILE_EXT" IS '파일타입';
COMMENT ON COLUMN "T_FILE"."FILE_TYPE" IS '파일타입';
COMMENT ON COLUMN "T_FILE"."MASTER_FILE_SEQ" IS '마스터파일';
COMMENT ON COLUMN "T_FILE"."CREATE_USER" IS '생성자';
COMMENT ON COLUMN "T_FILE"."CREATE_DATE" IS '생성일';
COMMENT ON COLUMN "T_FILE"."UPDATE_USER" IS '수정자';
COMMENT ON COLUMN "T_FILE"."UPDATE_DATE" IS '수정일';
