--------------------------------------------------------
--  DDL for Table T_AUTH
--------------------------------------------------------

  CREATE TABLE "T_ACCESS_AUTH" 
   (	"USER_ID" VARCHAR2(10), 
	"ACCESS_AUTH_TYPE" VARCHAR2(6), 
	"CREATE_USER" VARCHAR2(100), 
	"CREATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(100), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_DATA" 
;
   COMMENT ON COLUMN "T_ACCESS_AUTH"."USER_ID" IS '사원번호';
   COMMENT ON COLUMN "T_ACCESS_AUTH"."ACCESS_AUTH_TYPE" IS '사용자 권한';
   COMMENT ON COLUMN "T_ACCESS_AUTH"."CREATE_USER" IS '생성자';
   COMMENT ON COLUMN "T_ACCESS_AUTH"."CREATE_DATE" IS '생성일';
   COMMENT ON COLUMN "T_ACCESS_AUTH"."UPDATE_USER" IS '수정자';
   COMMENT ON COLUMN "T_ACCESS_AUTH"."UPDATE_DATE" IS '수정일';
--------------------------------------------------------
--  DDL for Table T_AUTH
--------------------------------------------------------

  CREATE TABLE "T_AUTH" 
   (	"AUTH_SEQ" NUMBER, 
	"AUTH_NM" VARCHAR2(100), 
	"AUTH_TYPE" VARCHAR2(6), 
	"PARENT_AUTH" VARCHAR2(20),
	"REMARK" VARCHAR2(500), 
	"IS_LOCK" VARCHAR2(1) DEFAULT 'N', 
	"CREATE_USER" VARCHAR2(100), 
	"CREATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(100), 
	"UPDATE_DATE" DATE
	
	
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_DATA" 
;
   COMMENT ON COLUMN "T_AUTH"."AUTH_SEQ" IS '권한번호';
   COMMENT ON COLUMN "T_AUTH"."AUTH_NM" IS '권한명';
   COMMENT ON COLUMN "T_AUTH"."AUTH_TYPE" IS '권한타입';
   COMMENT ON COLUMN "T_AUTH"."REMARK" IS '비고';
   COMMENT ON COLUMN "T_AUTH"."IS_LOCK" IS '잠금여부';
   COMMENT ON COLUMN "T_AUTH"."CREATE_USER" IS '생성자';
   COMMENT ON COLUMN "T_AUTH"."CREATE_DATE" IS '생성일';
   COMMENT ON COLUMN "T_AUTH"."UPDATE_USER" IS '수정자';
   COMMENT ON COLUMN "T_AUTH"."UPDATE_DATE" IS '수정일';
   
--------------------------------------------------------
--  DDL for Table T_AUTH_MENU
--------------------------------------------------------

  CREATE TABLE "T_AUTH_MENU" 
   (	"AUTH_MENU_SEQ" NUMBER, 
	"AUTH_SEQ" NUMBER, 
	"MENU_SEQ" NUMBER, 
	"CREATE_USER" VARCHAR2(100), 
	"CREATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(100), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_DATA" 
;
   COMMENT ON COLUMN "T_AUTH_MENU"."AUTH_MENU_SEQ" IS '메뉴권한번호';
   COMMENT ON COLUMN "T_AUTH_MENU"."AUTH_SEQ" IS '인증번호';
   COMMENT ON COLUMN "T_AUTH_MENU"."MENU_SEQ" IS '메뉴번호';
   COMMENT ON COLUMN "T_AUTH_MENU"."CREATE_USER" IS '생성자';
   COMMENT ON COLUMN "T_AUTH_MENU"."CREATE_DATE" IS '생성일';
   COMMENT ON COLUMN "T_AUTH_MENU"."UPDATE_USER" IS '수정자';
   COMMENT ON COLUMN "T_AUTH_MENU"."UPDATE_DATE" IS '수정일';
--------------------------------------------------------
--  DDL for Table T_AUTH_USER
--------------------------------------------------------

  CREATE TABLE "T_AUTH_USER" 
   (	"AUTH_USER_SEQ" NUMBER, 
	"AUTH_SEQ" NUMBER, 
	"USER_ID" VARCHAR2(20), 
	"CREATE_USER" VARCHAR2(100), 
	"CREATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(100), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_DATA" 
;
   COMMENT ON COLUMN "T_AUTH_USER"."AUTH_USER_SEQ" IS '사용자 권한 번호';
   COMMENT ON COLUMN "T_AUTH_USER"."AUTH_SEQ" IS '권한그룹번호';
   COMMENT ON COLUMN "T_AUTH_USER"."USER_ID" IS '사원번호';
   COMMENT ON COLUMN "T_AUTH_USER"."CREATE_USER" IS '생성자';
   COMMENT ON COLUMN "T_AUTH_USER"."CREATE_DATE" IS '생성일';
   COMMENT ON COLUMN "T_AUTH_USER"."UPDATE_USER" IS '수정자';
   COMMENT ON COLUMN "T_AUTH_USER"."UPDATE_DATE" IS '수정일';



  

