-- 인덱스 명칭에 대한 하나의 예시는 테이블 명과 컬럼명의 조합이다.

-- 1. INDEX 생성
--------------------------------------------------------
--  DDL for Index T_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_USER_PK" ON "T_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"
;
--------------------------------------------------------
--  DDL for Index IDX_MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_MENU_PK" ON "T_MENU" ("MENU_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"  
;
--------------------------------------------------------
--  DDL for Index IDX_COMMON_CODE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_COMMON_CODE_PK" ON "T_CODE" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"
;
--------------------------------------------------------
--  DDL for Index IDX_FILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_FILE_PK" ON "T_FILE" ("FILE_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"
;
--------------------------------------------------------
--  DDL for Index IDX_MANUAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_MANUAL_PK" ON "T_MANUAL" ("MANUAL_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"
;

--------------------------------------------------------
--  DDL for Index IDX_ACCESS_AUTH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_ACCESS_AUTH_PK" ON "T_ACCESS_AUTH" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"
;

--------------------------------------------------------
--  DDL for Index IDX_AUTH__PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_AUTH_PK" ON "T_AUTH" ("AUTH_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"
;

--------------------------------------------------------
--  DDL for Index IDX_AUTH_MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_AUTH_MENU_PK" ON "T_AUTH_MENU" ("AUTH_MENU_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"
;
--------------------------------------------------------
--  DDL for Index IDX_AUTH_MENU_GROUP_FK
--------------------------------------------------------

  CREATE INDEX "IDX_AUTH_MENU_AUTH_FK" ON "T_AUTH_MENU" ("AUTH_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"
;
--------------------------------------------------------
--  DDL for Index IDX_AUTH_MENU_MENU_FK
--------------------------------------------------------

  CREATE INDEX "IDX_AUTH_MENU_MENU_FK" ON "T_AUTH_MENU" ("MENU_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"
;
--------------------------------------------------------
--  DDL for Index IDX_AUTH_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_AUTH_USER_PK" ON "T_AUTH_USER" ("AUTH_USER_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"
;
--------------------------------------------------------
--  DDL for Index IDX_AUTH_USER_FK
--------------------------------------------------------

  CREATE INDEX "IDX_AUTH_USER_AUTH_FK" ON "T_AUTH_USER" ("AUTH_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"
;
--------------------------------------------------------
--  DDL for Index IDX_AUTH_USER_FK
--------------------------------------------------------

  CREATE INDEX "IDX_AUTH_USER_USER_FK" ON "T_AUTH_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"
;
