--------------------------------------------------------
--  Constraints for Table T_USER
--------------------------------------------------------

  ALTER TABLE "T_USER" ADD CONSTRAINT "IDX_USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"  ENABLE;
  ALTER TABLE "T_USER" MODIFY ("CREATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_USER" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_USER" MODIFY ("UPDATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_USER" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_USER" MODIFY ("USER_NM" NOT NULL ENABLE);
  ALTER TABLE "T_USER" MODIFY ("USER_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table T_MENU
--------------------------------------------------------

  ALTER TABLE "T_MENU" ADD CONSTRAINT "IDX_MENU_PK" PRIMARY KEY ("MENU_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"  ENABLE;
  ALTER TABLE "T_MENU" MODIFY ("CREATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_MENU" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_MENU" MODIFY ("UPDATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_MENU" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_MENU" MODIFY ("MENU_NM" NOT NULL ENABLE);
  ALTER TABLE "T_MENU" MODIFY ("MENU_SEQ" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table T_COMMON_CODE
--------------------------------------------------------

  ALTER TABLE "T_CODE" ADD CONSTRAINT "IDX_CODE_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"  ENABLE;
  ALTER TABLE "T_CODE" MODIFY ("CREATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_CODE" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_CODE" MODIFY ("UPDATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_CODE" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_CODE" MODIFY ("CODE_NM" NOT NULL ENABLE);
  ALTER TABLE "T_CODE" MODIFY ("CODE" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table T_FILE
--------------------------------------------------------

  ALTER TABLE "T_FILE" ADD CONSTRAINT "IDX_FILE_PK" PRIMARY KEY ("FILE_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"  ENABLE;
  ALTER TABLE "T_FILE" MODIFY ("CREATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_FILE" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_FILE" MODIFY ("UPDATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_FILE" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_FILE" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "T_FILE" MODIFY ("FILE_PATH" NOT NULL ENABLE);
  ALTER TABLE "T_FILE" MODIFY ("FILE_SEQ" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table T_MANUAL
--------------------------------------------------------

  ALTER TABLE "T_MANUAL" ADD CONSTRAINT "IDX_MANUAL_PK" PRIMARY KEY ("MANUAL_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"  ENABLE;
  ALTER TABLE "T_MANUAL" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "T_MANUAL" MODIFY ("CREATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_MANUAL" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_MANUAL" MODIFY ("UPDATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_MANUAL" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_MANUAL" MODIFY ("MANUAL_SEQ" NOT NULL ENABLE);


--------------------------------------------------------
--  Constraints for Table T_AUTH
--------------------------------------------------------

  ALTER TABLE "T_ACCESS_AUTH" ADD CONSTRAINT "IDX_ACCESS_AUTH_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"  ENABLE;
  ALTER TABLE "T_AUTH" MODIFY ("CREATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH" MODIFY ("UPDATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AUTH_GROUP
--------------------------------------------------------

  ALTER TABLE "T_AUTH" ADD CONSTRAINT "IDX_AUTH_PK" PRIMARY KEY ("AUTH_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"  ENABLE;
  ALTER TABLE "T_AUTH_GROUP" MODIFY ("CREATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_GROUP" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_GROUP" MODIFY ("UPDATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_GROUP" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_GROUP" MODIFY ("AUTH_NM" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_GROUP" MODIFY ("AUTH_SEQ" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AUTH_MENU
--------------------------------------------------------

  ALTER TABLE "T_AUTH_MENU" ADD CONSTRAINT "IDX_AUTH_MENU_PK" PRIMARY KEY ("AUTH_MENU_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"  ENABLE;
  ALTER TABLE "T_AUTH_MENU" MODIFY ("CREATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_MENU" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_MENU" MODIFY ("UPDATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_MENU" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_MENU" MODIFY ("AUTH_SEQ" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_MENU" MODIFY ("MENU_SEQ" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_MENU" MODIFY ("AUTH_MENU_SEQ" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_AUTH_USER
--------------------------------------------------------

  ALTER TABLE "T_AUTH_USER" ADD CONSTRAINT "IDX_AUTH_USER_PK" PRIMARY KEY ("AUTH_USER_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PLATFORM_IDX"  ENABLE;
  ALTER TABLE "T_AUTH_USER" MODIFY ("CREATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_USER" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_USER" MODIFY ("UPDATE_USER" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_USER" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_USER" MODIFY ("IS_DEL" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_USER" MODIFY ("GROUP_SEQ" NOT NULL ENABLE);
  ALTER TABLE "T_AUTH_USER" MODIFY ("AUTH_USER_SEQ" NOT NULL ENABLE);


